# Generated by Django 4.2.3 on 2023-07-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non Fiction'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Biography', 'Biography'), ('History', 'History'), ('Poetry', 'Poetry'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Children', 'Children'), ('Self-Help', 'Self Help'), ('Religion/Spirituality', 'Religion Spirituality'), ('Cookbook', 'Cookbook'), ('Travel', 'Travel'), ('Art', 'Art'), ('Sports', 'Sports'), ('Other', 'Other')], default='Other', max_length=30)),
                ('isbn', models.CharField(max_length=100)),
                ('availability_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('member_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.member')),
            ],
            options={
                'unique_together': {('book', 'member')},
            },
        ),
    ]
