# Generated by Django 4.2.3 on 2023-07-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non Fiction'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Fantasy', 'Fantasy'), ('Science Fiction', 'Science Fiction'), ('Science', 'Science'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Biography', 'Biography'), ('History', 'History'), ('Poetry', 'Poetry'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Children', 'Children'), ('Self-Help', 'Self Help'), ('Religion/Spirituality', 'Religion Spirituality'), ('Cookbook', 'Cookbook'), ('Travel', 'Travel'), ('Art', 'Art'), ('Sports', 'Sports'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
