# Generated by Django 4.2.3 on 2023-07-31 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_name',
            new_name='member',
        ),
    ]
