# Generated by Django 4.2.3 on 2023-07-31 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_member_name_member_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_ID',
        ),
    ]
