# Generated by Django 4.2.3 on 2023-07-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_member_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
