# Generated by Django 4.2.3 on 2023-07-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowedbook',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='member',
            name='member',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ReturnedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.member')),
            ],
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='returned_date',
        ),
    ]
