# Generated by Django 4.2.3 on 2023-07-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_borrowedbook_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='returnedbook',
            name='member',
        ),
        migrations.AddField(
            model_name='returnedbook',
            name='book_detail',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='books.borrowedbook'),
            preserve_default=False,
        ),
    ]
