# Generated by Django 4.2.3 on 2023-07-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_returnedbook_book_remove_returnedbook_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
    ]
