# Generated by Django 4.2.3 on 2023-08-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedbook',
            name='book_detail',
        ),
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
        migrations.DeleteModel(
            name='ReturnedBook',
        ),
    ]
