# Generated by Django 4.2.3 on 2023-08-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_status',
            new_name='BookStatus',
        ),
    ]
