# Generated by Django 4.2.3 on 2023-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_rename_book_status_bookstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstatus',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
