# Generated by Django 4.2.3 on 2023-08-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_bookstatus_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
