# Generated by Django 4.2.3 on 2023-08-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_published_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member',
            field=models.CharField(max_length=100),
        ),
    ]
