# Generated by Django 4.2.3 on 2023-08-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_member_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_year',
        ),
    ]
